# Common settings
[common]
http_timeout=60
#update_tag="<CHANGEME>"
permission_relationships_file="cartography/data/permission_relationships.yaml"
[neo4j]
uri="bolt://localhost:7687"
#user="neo4j"
#password="neo4j"
password_prompt=false
max_connection_lifetime=3600
database="neo4j"
[analysis]
#job_directory
[aws]
#sync_all_profiles=True
#best_effort_mode=True
#requested_syncs=ec2,iam,lambda,rds,s3,sqs,sts
[azure]
#sync_all_subscriptions=True
#sp_auth=True
#tenant_id=""
#client_id=""
#client_secret=""
[bigfix]
#username=""
#password=""
#root_url=""
[crowdstrike]
#client_id=""
#client_secret=""
#api_url=""
[cve]
#enabled=true
#url="https://services.nvd.nist.gov/rest/json/cves/2.0/"
#api_key=""
[digitalocean]
#token=""
[duo]
#api_key=""
#api_secret=""
#api_hostname=""
[github]
#org1.token=""
#org1.url=""
[gsuite]
#auth_method=""
#delegated_admin=""
#settings_account_file=""
#client_id=""
#client_secret=""
#refresh_token=""
#token_uri=""
[jamf]
#base_url=""
#user=""
#password=""
[k8s]
#kubeconfig=""
[kandji]
#base_url=""
#tenant_id=""
#token=""
[lastpass]
#cid=""
#provhash=""
[okta]
#saml_role_regex="^aws\#\S+\#(?{{role}}[\w\-]+)\#(?{{accountid}}\d+)$"
#api_key=""
#org_id=""
[pagerduty]
#api_key=""
[semgrep]
#token=""
#dependency_ecosystems="gomod,npm,pypi"
[snipeit]
#base_url=""
#token=""
#tenant_id=""
